import type { Item, Weapon } from '../types';
import { ItemType } from '../types';
import { NEXT_DUNGEON, NEXT_TURN, TRADE } from './ItemLogic';

export const magicItems: Item[] = [
  {
    id: 'healing_herbs',
    name: 'items.magicItems.healingHerbs.name',
    nameTranslationKey: 'items.magicItems.healingHerbs.name',
    type: ItemType.MAGIC,
    value: 0,
    amountInDeck: 1,
    properties: {
      USED: false,
      ACTIVE: true,
      DESCRIPTION: 'items.magicItems.healingHerbs.description',
      RESET_ON: [TRADE, NEXT_DUNGEON],
    },
    effect: 'magicHerbsOnUse',
    reset: 'magicHerbsOnReset',
  },
  {
    id: 'boots_of_speed',
    name: 'items.magicItems.boots.name',
    nameTranslationKey: 'items.magicItems.boots.name',
    type: ItemType.MAGIC,
    value: 0,
    amountInDeck: 1,
    properties: {
      DESCRIPTION: 'items.magicItems.boots.description',
      MOVEMENT_BONUS: 1,
    },
    pickup: 'movementBonusOnPickup',
    drop: 'movementBonusOnDrop',
  },
  {
    id: 'giants_glove',
    name: 'items.magicItems.giantsGlove.name',
    nameTranslationKey: 'items.magicItems.giantsGlove.name',
    type: ItemType.MAGIC,
    value: 0,
    amountInDeck: 1,
    properties: {
      DESCRIPTION: 'items.magicItems.giantsGlove.description',
      BREAK_DOOR: true,
      ATTACK_BONUS: 1,
    },
  },
  {
    id: 'ring_of_precision',
    name: 'items.magicItems.ringOfPrecision.name',
    nameTranslationKey: 'items.magicItems.ringOfPrecision.name',
    type: ItemType.MAGIC,
    value: 0,
    amountInDeck: 1,
    properties: {
      DESCRIPTION: 'items.magicItems.ringOfPrecision.description',
      RE_ROLL_ATTACK: true,
    },
  },
  {
    id: 'crown_of_wisdom',
    name: 'items.magicItems.crownOfWisdom.name',
    nameTranslationKey: 'items.magicItems.crownOfWisdom.name',
    type: ItemType.MAGIC,
    value: 0,
    amountInDeck: 1,
    properties: {
      DESCRIPTION: 'items.magicItems.crownOfWisdom.description',
      SEARCH_BONUS: 1,
    },
  },
  {
    id: 'sword_of_chaos',
    name: 'items.magicItems.swordOfChaos.name',
    nameTranslationKey: 'items.magicItems.swordOfChaos.name',
    type: ItemType.MAGIC,
    value: 0,
    amountInDeck: 1,
    properties: {
      DESCRIPTION: 'items.magicItems.swordOfChaos.description',
    },
    effect: 'chaosSwordOnUse',
    // Weapon properties so the sword can be equipped in hero.weapon and used via attack()
    dice: 4,
    range: 1,
    twoHanded: false,
    useHearHeroes: true,
    ignoresShield: true,
    ignoresArmour: true,
  } as Item & Weapon,
  {
    id: 'potion_of_speed',
    name: 'items.magicItems.potionOfSpeed.name',
    nameTranslationKey: 'items.magicItems.potionOfSpeed.name',
    type: ItemType.MAGIC,
    value: 0,
    amountInDeck: 1,
    properties: {
      DESCRIPTION: 'items.magicItems.potionOfSpeed.description',
      USED: false,
      ACTIONS_BONUS: 2,
      ACTIVE: true,
    },
    effect: 'potionOfSpeedOnUse',
  },
  {
    id: 'necklace_of_light',
    name: 'items.magicItems.necklaceOfLight.name',
    nameTranslationKey: 'items.magicItems.necklaceOfLight.name',
    type: ItemType.MAGIC,
    value: 0,
    amountInDeck: 1,
    properties: {
      USED: false,
      RESET_ON: [NEXT_TURN],
      ACTIVE: true,
      DESCRIPTION: 'items.magicItems.necklaceOfLight.description',
    },
    effect: 'necklaceOfLightOnUse',
    reset: 'necklaceOfLightOnReset',
  },
];
