import type { Weapon } from '../types';
import { ItemType } from '../types';

export const weapons: Weapon[] = [
  {
    id: 'sword',
    name: 'items.weapons.sword',
    nameTranslationKey: 'items.weapons.sword',
    range: 1,
    dice: 3,
    twoHanded: false,
    useHearHeroes: true,
    amountInDeck: 0,
    type: ItemType.WEAPON,
    value: 0,
    ignoresShield: false,
    ignoresArmour: false,
  },
  {
    id: 'two_handed_sword',
    name: 'items.weapons.twoHandedSword',
    nameTranslationKey: 'items.weapons.twoHandedSword',
    range: 1,
    dice: 4,
    twoHanded: true,
    useHearHeroes: false,
    amountInDeck: 1,
    type: ItemType.WEAPON,
    value: 3,
    ignoresShield: false,
    ignoresArmour: false,
  },
  {
    id: 'halberd',
    name: 'items.weapons.halberd',
    nameTranslationKey: 'items.weapons.halberd',
    range: 2,
    dice: 3,
    twoHanded: true,
    useHearHeroes: true,
    amountInDeck: 1,
    type: ItemType.WEAPON,
    value: 2,
    ignoresShield: false,
    ignoresArmour: false,
  },
  {
    id: 'flail',
    name: 'items.weapons.flail',
    nameTranslationKey: 'items.weapons.flail',
    range: 1,
    dice: 4,
    twoHanded: false,
    useHearHeroes: true,
    amountInDeck: 1,
    type: ItemType.WEAPON,
    value: 4,
    ignoresShield: false,
    ignoresArmour: false,
  },
  {
    id: 'double_headed_axe',
    name: 'items.weapons.doubleHeadedAxe',
    nameTranslationKey: 'items.weapons.doubleHeadedAxe',
    range: 1,
    dice: 4,
    twoHanded: true,
    useHearHeroes: true,
    amountInDeck: 1,
    type: ItemType.WEAPON,
    value: 3,
    ignoresShield: false,
    ignoresArmour: false,
  },
];

export const monsterWeapons: Weapon[] = [
  {
    id: 'orc_sword',
    name: 'items.weapons.orchSword',
    nameTranslationKey: 'items.weapons.orchSword',
    range: 1,
    dice: 3,
    twoHanded: false,
    useHearHeroes: true,
    amountInDeck: 4,
    type: ItemType.WEAPON,
    value: 0,
    ignoresShield: false,
    ignoresArmour: false,
  },
  {
    id: 'orc_bow',
    name: 'items.weapons.orchBow',
    nameTranslationKey: 'items.weapons.orchBow',
    range: 999,
    dice: 3,
    twoHanded: false,
    useHearHeroes: true,
    amountInDeck: 4,
    type: ItemType.WEAPON,
    value: 0,
    ignoresShield: true,
    ignoresArmour: false,
  },
  {
    id: 'troll_club',
    name: 'items.weapons.trollClub',
    nameTranslationKey: 'items.weapons.trollClub',
    range: 1,
    dice: 3,
    twoHanded: false,
    useHearHeroes: true,
    amountInDeck: 4,
    type: ItemType.WEAPON,
    value: 0,
    ignoresShield: false,
    ignoresArmour: false,
  },
  {
    id: 'dark_lord_sword',
    name: 'items.weapons.darkLordSword',
    nameTranslationKey: 'items.weapons.darkLordSword',
    range: 1,
    dice: 3,
    twoHanded: false,
    useHearHeroes: true,
    amountInDeck: 3,
    type: ItemType.WEAPON,
    value: 0,
    ignoresShield: false,
    ignoresArmour: false,
  },
  {
    id: 'green_dark_lord_sword',
    name: 'items.weapons.greenDarkLordSword',
    nameTranslationKey: 'items.weapons.greenDarkLordSword',
    range: 1,
    dice: 3,
    twoHanded: false,
    useHearHeroes: true,
    amountInDeck: 1,
    type: ItemType.WEAPON,
    value: 0,
    ignoresShield: false,
    ignoresArmour: false,
  },
];
