import type { TurnEvent } from '../types';

export const events: TurnEvent[] = [
  {
    id: 'hungry_troll',
    type: 'HUNGRY_TROLL',
    name: 'events.hungryTroll.name',
    nameTranslationKey: 'events.hungryTroll.name',
    number: 1,
    description: 'events.hungryTroll.description',
    descriptionTranslationKey: 'events.hungryTroll.description',
    effect: 'theHungryTroll',
    used: false,
  },
  {
    id: 'sun_stone',
    type: 'SUN_STONE',
    name: 'events.sunStone.name',
    nameTranslationKey: 'events.sunStone.name',
    number: 2,
    description: 'events.sunStone.description',
    descriptionTranslationKey: 'events.sunStone.description',
    effect: 'sunStone',
    used: false,
  },
  {
    id: 'time_portal',
    type: 'TIME_PORTAL',
    name: 'events.timePortal.name',
    nameTranslationKey: 'events.timePortal.name',
    number: 3,
    description: 'events.timePortal.description',
    descriptionTranslationKey: 'events.timePortal.description',
    effect: 'timePortal',
    used: false,
  },
  {
    id: 'fountain_of_youth',
    type: 'FOUNTAIN_OF_YOUTH',
    name: 'events.fountainOfYouth.name',
    nameTranslationKey: 'events.fountainOfYouth.name',
    number: 4,
    description: 'events.fountainOfYouth.description',
    descriptionTranslationKey: 'events.fountainOfYouth.description',
    effect: 'fountainOfYouth',
    used: false,
  },
  {
    id: 'sleeping_gas',
    type: 'SLEEPING_GAS_CLOUD',
    name: 'events.sleepingGas.name',
    nameTranslationKey: 'events.sleepingGas.name',
    number: 5,
    description: 'events.sleepingGas.description',
    descriptionTranslationKey: 'events.sleepingGas.description',
    effect: 'sleepingGasCloud',
    used: false,
  },
  {
    id: 'lost_orc',
    type: 'LOST_ORC',
    name: 'events.lostOrch.name',
    nameTranslationKey: 'events.lostOrch.name',
    number: 6,
    description: 'events.lostOrch.description',
    descriptionTranslationKey: 'events.lostOrch.description',
    effect: 'theLostOrch',
    used: false,
  },
  {
    id: 'dragons_breath',
    type: 'DRAGONS_BREATH',
    name: 'events.dragonsBreath.name',
    nameTranslationKey: 'events.dragonsBreath.name',
    number: 7,
    description: 'events.dragonsBreath.description',
    descriptionTranslationKey: 'events.dragonsBreath.description',
    effect: 'theDragonsBreath',
    used: false,
  },
  {
    id: 'landslide',
    type: 'LANDSLIDE',
    name: 'events.landslide.name',
    nameTranslationKey: 'events.landslide.name',
    number: 8,
    description: 'events.landslide.description',
    descriptionTranslationKey: 'events.landslide.description',
    effect: 'landslide',
    used: false,
  },
  {
    id: 'magic_node',
    type: 'MAGIC_NODE',
    name: 'events.magicNode.name',
    nameTranslationKey: 'events.magicNode.name',
    number: 9,
    description: 'events.magicNode.description',
    descriptionTranslationKey: 'events.magicNode.description',
    effect: 'fountainOfYouth',
    used: false,
  },
  {
    id: 'foresight',
    type: 'FORESIGHT',
    name: 'events.foresight.name',
    nameTranslationKey: 'events.foresight.name',
    number: 10,
    description: 'events.foresight.description',
    descriptionTranslationKey: 'events.foresight.description',
    effect: 'foresight',
    used: false,
  },
  {
    id: 'earthquake',
    type: 'EARTHQUAKE',
    name: 'events.earthquake.name',
    nameTranslationKey: 'events.earthquake.name',
    number: 11,
    description: 'events.earthquake.description',
    descriptionTranslationKey: 'events.earthquake.description',
    effect: 'earthquake',
    used: false,
  },
  {
    id: 'magic_storm',
    type: 'MAGIC_STORM',
    name: 'events.magicStorm.name',
    nameTranslationKey: 'events.magicStorm.name',
    number: 12,
    description: 'events.magicStorm.description',
    descriptionTranslationKey: 'events.magicStorm.description',
    effect: 'theMagicStorm',
    used: false,
  },
  {
    id: 'elemental_weapon',
    type: 'ELEMENTAL_WEAPON',
    name: 'events.elementalWeapon.name',
    nameTranslationKey: 'events.elementalWeapon.name',
    number: 13,
    description: 'events.elementalWeapon.description',
    descriptionTranslationKey: 'events.elementalWeapon.description',
    effect: 'theElementalWeapon',
    used: false,
  },
  {
    id: 'orc_drums',
    type: 'ORC_DRUMS',
    name: 'events.orchDrums.name',
    nameTranslationKey: 'events.orchDrums.name',
    number: 14,
    description: 'events.orchDrums.description',
    descriptionTranslationKey: 'events.orchDrums.description',
    effect: 'theOrchDrums',
    used: false,
  },
  {
    id: 'weakness',
    type: 'SYMBOL_OF_WEAKNESS',
    name: 'events.weakness.name',
    nameTranslationKey: 'events.weakness.name',
    number: 15,
    description: 'events.weakness.description',
    descriptionTranslationKey: 'events.weakness.description',
    effect: 'theSymbolOfWeakness',
    used: false,
  },
  {
    id: 'hexagram',
    type: 'HEXAGRAM',
    name: 'events.hexagram.name',
    nameTranslationKey: 'events.hexagram.name',
    number: 16,
    description: 'events.hexagram.description',
    descriptionTranslationKey: 'events.hexagram.description',
    effect: 'theHexagram',
    used: false,
  },
];
