import type { TurnEvent } from '../types';

export const events: TurnEvent[] = [
  {
    name: 'events.hungryTroll.name',
    number: 1,
    description: 'events.hungryTroll.description',
    effect: 'theHungryTroll',
    used: false,
  },
  {
    name: 'events.sunStone.name',
    number: 2,
    description: 'events.sunStone.description',
    effect: 'sunStone',
    used: false,
  },
  {
    name: 'events.timePortal.name',
    number: 3,
    description: 'events.timePortal.description',
    effect: 'timePortal',
    used: false,
  },
  {
    name: 'events.fountainOfYouth.name',
    number: 4,
    description: 'events.fountainOfYouth.description',
    effect: 'fountainOfYouth',
    used: false,
  },
  {
    name: 'events.sleepingGas.name',
    number: 5,
    description: 'events.sleepingGas.description',
    effect: 'sleepingGasCloud',
    used: false,
  },
  {
    name: 'events.lostOrch.name',
    number: 6,
    description: 'events.lostOrch.description',
    effect: 'theLostOrch',
    used: false,
  },
  {
    name: 'events.dragonsBreath.name',
    number: 7,
    description: 'events.dragonsBreath.description',
    effect: 'theDragonsBreath',
    used: false,
  },
  {
    name: 'events.landslide.name',
    number: 8,
    description: 'events.landslide.description',
    effect: 'landslide',
    used: false,
  },
  {
    name: 'events.magicNode.name',
    number: 9,
    description: 'events.magicNode.description',
    effect: 'fountainOfYouth',
    used: false,
  },
  {
    name: 'events.foresight.name',
    number: 10,
    description: 'events.foresight.description',
    effect: 'foresight',
    used: false,
  },
  {
    name: 'events.earthquake.name',
    number: 11,
    description: 'events.earthquake.description',
    effect: 'earthquake',
    used: false,
  },
  {
    name: 'events.magicStorm.name',
    number: 12,
    description: 'events.magicStorm.description',
    effect: 'theMagicStorm',
    used: false,
  },
  {
    name: 'events.elementalWeapon.name',
    number: 13,
    description: 'events.elementalWeapon.description',
    effect: 'theElementalWeapon',
    used: false,
  },
  {
    name: 'events.orchDrums.name',
    number: 14,
    description: 'events.orchDrums.description',
    effect: 'theOrchDrums',
    used: false,
  },
  {
    name: 'events.weakness.name',
    number: 15,
    description: 'events.weakness.description',
    effect: 'theSymbolOfWeakness',
    used: false,
  },
];
