import type { Dungeon } from '../../types';
import { ConditionType, SecretType, Side } from '../../types';
import {
  createDoor,
  createEquipment,
  createHiddenDoor,
  createLockedDoor,
  createSecret,
  createTrappedDoor,
  createTrappedHiddenDoor,
  createTrappedLockedDoor,
} from '../../dungeon/DungeonLogic';
import { weapons } from '../../items/weapons';

export const e1m4: Dungeon = {
  name: 'campaign.iceDragon.e1m4.name',
  beaten: false,
  winConditions: [
    {
      type: ConditionType.KILL_AT_LEAST,
      killMinCount: 7,
      fulfilled: false,
    },
    {
      type: ConditionType.KILL_ALL,
      fulfilled: false,
    },
    {
      type: ConditionType.REACH_CELL,
      fulfilled: false,
      targetCell: { x: 16, y: 11 },
    },
  ],
  startingPositions: [
    { x: 3, y: 2 },
    { x: 2, y: 1 },
    { x: 2, y: 2 },
    { x: 2, y: 3 },
  ],
  discoveredRooms: ['A'],
  layout: {
    grid: [
      ' ##### ########   ',
      ' #AAA###CCCCCC#   ',
      ' #AAABBBCCCCCC#   ',
      ' #AAA###CCCCCC#   ',
      ' ##D## #####G##   ',
      '  #D#  #####G##   ',
      '###D## #####G##   ',
      '#EEEE###HHHHHH#   ',
      '#EEEEFFFHHHHHH#   ',
      '##L#####HHHHHH####',
      '##L#NNN#HHHHHHIII#',
      '##L#NNN####K##III#',
      '#MMMNNN####K##III#',
      '#MMM#######K###J##',
      '#MMM###PPPPPPPJJ##',
      '#MMMPPPPPPPPPP####',
      '#######PPPPPPP#   ',
      '      #########   ',
    ],
    corridors: ['B', 'D', 'G', 'F', 'L', 'K', 'J'],
    pits: [],
    doors: [
      createDoor(Side.DOWN, 3, 3),
      createLockedDoor(Side.RIGHT, 4, 2),
      createDoor(Side.RIGHT, 7, 2),
      createLockedDoor(Side.DOWN, 12, 3),
      createDoor(Side.DOWN, 3, 6),
      createDoor(Side.DOWN, 12, 6),
      createHiddenDoor(Side.DOWN, 2, 8),
      createTrappedLockedDoor(Side.RIGHT, 4, 8, 2),
      createDoor(Side.RIGHT, 7, 8),
      createDoor(Side.DOWN, 11, 10),
      createDoor(Side.DOWN, 2, 11),
      createHiddenDoor(Side.RIGHT, 3, 12),
      createDoor(Side.DOWN, 3, 15),
      createTrappedDoor(Side.DOWN, 11, 13, 2),
      createTrappedHiddenDoor(Side.RIGHT, 13, 10, 2),
      createTrappedHiddenDoor(Side.RIGHT, 13, 14, 2),
      createHiddenDoor(Side.UP, 15, 13),
    ],
    monsters: [],
    secrets: [
      createSecret(
        SecretType.NOTE,
        'campaign.iceDragon.e1m4.secrets.note1',
        13,
        2,
      ),
      createSecret(
        SecretType.EQUIPMENT,
        'campaign.iceDragon.randomEquipment',
        4,
        10,
      ),
      createSecret(SecretType.TRAP_DOOR, 'campaign.iceDragon.trapDoor', 5, 15),
      createSecret(SecretType.TRAP_DOOR, 'campaign.iceDragon.trapDoor', 14, 10),
      createSecret(SecretType.TRAP_DOOR, 'campaign.iceDragon.trapDoor', 15, 11),
      createSecret(SecretType.TRAP_DOOR, 'campaign.iceDragon.trapDoor', 14, 12),
    ],
    notes: [
      {
        position: { x: 11, y: 8 },
        message: 'campaign.iceDragon.e1m4.notes.liberVortex',
      },
      {
        position: { x: 13, y: 10 },
        message: 'campaign.iceDragon.e1m4.notes.ironDoor',
      },
    ],
    items: [createEquipment(3, 8, weapons[1])],
  },
  killCount: 0,
  events: [],
};
